# Generated by Django 5.1.2 on 2024-10-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment')], max_length=10)),
                ('wifi', models.BooleanField(default=False)),
                ('washer', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('smoking', models.BooleanField(default=False)),
                ('host_language', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
